### ISSUE TITLE
Feature suggestion - Allow specifying database and port for `cb uri`

### ISSUE THREAD

**Issue by mt-rorykelly** [CrunchyData/bridge-cli#138]
Currently `cb uri` gives a `--role` option for specifying the role to use with the URI, but the database will always be `postgres` and the port will always be `5432`.

It would be nice to be able to provide `--database` argument and an argument to use port `5431` to make it a pool uri.

For now because the port and database are predictable I can just use `sed` to replace them, so it is not a blocker. But it would be a nicer experience to be able to build the URI using `cb uri` alone instead of needing to replace parts with sed.

**Comment by abrightwell** [comment]
Thanks for the feedback @mt-rorykelly. Both seem like reasonable expectations. I'll add it to the list to bring up for discussion. 👍

**Comment by abrightwell** [comment]
Fixed in [v3.4.1](https://github.com/CrunchyData/bridge-cli/releases/tag/v3.4.1).

**Comment by mt-rorykelly** [comment]
I didn't notice that this was implemented for now. Thank you for implementing the suggestion.
