### ISSUE TITLE
cb login should show login URL when it cannot open a browser

### ISSUE THREAD

**Issue by gaffneyc** [CrunchyData/bridge-cli#139]
I often use a headless linux server for development and after upgrading to 3.4.0 it fails since I don't have the `xdg-open` command.

```bash
$ cb login
Press any key to open a browser to login or q to exit:
error: Command 'xdg-open' could not be found.
```

```bash
$ cb version
cb v3.4.0 (unknown sha)
```

**Comment by abrightwell** [comment]
This is good feedback. We'll add this. Thanks!

Also, note that you can use an API key to authenticate requests as well.  By setting the env `CB_API_KEY` with a key that you can obtain through the dashboard you can bypass the `cb login` flow. Adding this env was meant to facilitate the headless and/or scripted use of the tool.  Regardless, presenting the URL is something we will definitely add in our next update/release.
