### ISSUE TITLE
Does brew install get an arm64 binary on macintosh?

### ISSUE THREAD

**Issue by fdr** [CrunchyData/bridge-cli#157]
When following https://docs.crunchybridge.com/quickstart/cli on an arm64 macintosh, I believe it gets a x64 binary instead, and then crashes with something like "invalid instruction". 

Probably there should be an arm64 build for mac, but if not, exiting brew install with a message rather than getting an illegal instruction type of error would be better.

I'm reporting on behalf of another, I would be more definitive, but I do not have easy access to an arm64 macintosh

**Comment by abrightwell** [comment]
Hmm... it should be an arm64 compatible binary. I'll look into it though. Thanks.

**Comment by fdr** [comment]
I did confirm the fault with something like `file $(which cb)` and it did say an x64 binary. This was on a somewhat pedestrian macbook, though perhaps newish?

**Comment by abrightwell** [comment]
Fixed in v3.5.1.
