### ISSUE TITLE
cb psql is broken on prompt1

### ISSUE THREAD

**Issue by sobrinho** [CrunchyData/bridge-cli#165]
The terminal gets fuzzy and breaks the REPL.

Setting the PROMPT1 to something else like: `\set PROMPT1 '(%n@%M:%>) %`date +%H:%M:%S` [%/] \n%x%# '` fix the issue.

Probably it's missing a clear char or even adding the breakline will fix the issue.

**Comment by abrightwell** [comment]
@sobrinho what version are you using?

**Comment by sobrinho** [comment]
Seems fixed now, thanks!

**Comment by abrightwell** [comment]
Good to hear! Thanks!
